// All icons are Lucide React — re-exported with legacy names for backward compat.
export {
  LayoutDashboard as DashboardIcon,
  Plus as PlusIcon,
  Download as DownloadIcon,
  Sparkles as SparkleIcon,
  File as FileIcon,
  LogOut as LogoutIcon,
  Pencil as EditIcon,
  ArrowRight as ArrowRightIcon,
  ChevronLeft as ChevronLeftIcon,
  Trash2 as TrashIcon,
  Link as LinkIcon,
  CheckCircle2 as CheckCircleIcon,
  Clock as ClockIcon,
  AlertTriangle as AlertIcon,
  X as Cross,
  ChevronDown as ChevronDownIcon,
  ChevronRight as ChevronRightIcon,
  Send as SendIcon,
  Paperclip as PaperclipIcon,
  Folder as FolderIcon,
  Table as TableIcon,
  Lock as LockIcon,
  Info as InfoIcon,
  ExternalLink as ExternalLinkIcon,
  LayoutGrid as GridIcon,
} from "lucide-react";
